---
- hosts: localhost
  vars:
    hostname: what-to-do
    setup_sanoid: false
    setup_syncoid: false
    install_zfs: false

  roles:
    - role: zfs
      become: true
      tags:
        - zfs
    - role: sanoid-and-syncoid
      become: true
      tags:
        - sanoid
        - oids
